#!/bin/sh

cd ..
#Copy implemented hooks 
for file in `ls -1 Hooks`
do
 if [ $file != "InstallHooks" ]; then
   echo $file 
   cp hooks/$file .git/hooks/$file
   sudo chmod +x .git/hooks/$file
 fi
done
